services:
    api:
        build: ./api
        restart: unless-stopped
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        ports:
            - 3000:3000
            - 9229:9229
        command: npm run development
        dns:
            - 8.8.8.8
            - 8.8.4.4
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
    web:
        build: ./web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        ports:
            - 80:80 # webpack dev server
        command: npm run development
volumes:
    node_modules_web:
    node_modules_api:
