services:
    api:
        build: ./api
        restart: unless-stopped
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        ports:
            - ${API_PORT:-3000}:3000
            - 127.0.0.1:${API_INSPECT_PORT:-9229}:9229
        command: npm run development
        depends_on:
            - mysql
    web:
        build: ./web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        ports:
            - ${WEB_PORT:-80}:80 # webpack dev server
        command: npm run development
        depends_on:
            - api
    mysql:
        image: mysql:8.2
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 127.0.0.1:${MYSQL_PORT:-3306}:3306
        volumes:
            - ./api:/app
            - mysql:/var/lib/mysql
            - ./api/data/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
    node_modules_web:
    node_modules_api:
    mysql:
