services:
    api:
        build: ./api
        restart: unless-stopped
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: academic
            DB_PASSWORD: academic
            DB_NAME: academic_events
        ports:
            - 3000:3000
            - 9229:9229
        command: npm run development
        dns:
            - 8.8.8.8
            - 8.8.4.4
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
        depends_on:
            - db
    web:
        build: ./web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        environment:
            API_URL: http://api:3000
        ports:
            - 80:80 # webpack dev server
        command: npm run development
        depends_on:
            - api
    db:
        image: mysql:8.2
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: academic_events
            MYSQL_USER: academic
            MYSQL_PASSWORD: academic
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
volumes:
    node_modules_web:
    node_modules_api:
    db_data:
